SET IDENTITY_INSERT [dbo].[Items] ON
INSERT INTO [dbo].[Items] ([ItemId], [CategoryId], [Title], [Price], [ItemArtUrl], [ProducerId]) VALUES (1, 1, N'Boost 350 V2 "Blue Tint"', CAST(435.00 AS Decimal(18, 2)), NULL, 1)
INSERT INTO [dbo].[Items] ([ItemId], [CategoryId], [Title], [Price], [ItemArtUrl], [ProducerId]) VALUES (2, 1, N'Boost 350 V2 "Zebra"', CAST(610.00 AS Decimal(18, 2)), NULL, 1)
INSERT INTO [dbo].[Items] ([ItemId], [CategoryId], [Title], [Price], [ItemArtUrl], [ProducerId]) VALUES (3, 1, N'Boost 350 V2 "Beluga 2.0"', CAST(415.00 AS Decimal(18, 2)), NULL, 1)
INSERT INTO [dbo].[Items] ([ItemId], [CategoryId], [Title], [Price], [ItemArtUrl], [ProducerId]) VALUES (4, 1, N'Boost 350 V2 "Pirate Black"', CAST(1245.00 AS Decimal(18, 2)), NULL, 1)
INSERT INTO [dbo].[Items] ([ItemId], [CategoryId], [Title], [Price], [ItemArtUrl], [ProducerId]) VALUES (6, 1, N'Boost 350 "MoonRock"', CAST(1260.00 AS Decimal(18, 2)), NULL, 1)
INSERT INTO [dbo].[Items] ([ItemId], [CategoryId], [Title], [Price], [ItemArtUrl], [ProducerId]) VALUES (8, 2, N'Retro 1 "Banned" 2011', CAST(750.00 AS Decimal(18, 2)), NULL, 2)
INSERT INTO [dbo].[Items] ([ItemId], [CategoryId], [Title], [Price], [ItemArtUrl], [ProducerId]) VALUES (9, 2, N'Retro 3 OG "Black Cement"', CAST(220.00 AS Decimal(18, 2)), NULL, 2)
INSERT INTO [dbo].[Items] ([ItemId], [CategoryId], [Title], [Price], [ItemArtUrl], [ProducerId]) VALUES (10, 2, N'Retro 4 "MotorSport"', CAST(150.00 AS Decimal(18, 2)), NULL, 2)
INSERT INTO [dbo].[Items] ([ItemId], [CategoryId], [Title], [Price], [ItemArtUrl], [ProducerId]) VALUES (11, 2, N'Retro 11 Bred 2012 ', CAST(525.00 AS Decimal(18, 2)), NULL, 2)
INSERT INTO [dbo].[Items] ([ItemId], [CategoryId], [Title], [Price], [ItemArtUrl], [ProducerId]) VALUES (12, 2, N'Retro 11 Bred Concord "Space Jam"', CAST(280.00 AS Decimal(18, 2)), NULL, 2)
INSERT INTO [dbo].[Items] ([ItemId], [CategoryId], [Title], [Price], [ItemArtUrl], [ProducerId]) VALUES (14, 3, N' Foamposite "Chinese New Year"', CAST(685.00 AS Decimal(18, 2)), NULL, 3)
INSERT INTO [dbo].[Items] ([ItemId], [CategoryId], [Title], [Price], [ItemArtUrl], [ProducerId]) VALUES (16, 3, N'Foamposite "Galaxy"', CAST(1500.00 AS Decimal(18, 2)), NULL, 3)
INSERT INTO [dbo].[Items] ([ItemId], [CategoryId], [Title], [Price], [ItemArtUrl], [ProducerId]) VALUES (17, 3, N'Foamposite "Gone Fishing"', CAST(300.00 AS Decimal(18, 2)), NULL, 3)
INSERT INTO [dbo].[Items] ([ItemId], [CategoryId], [Title], [Price], [ItemArtUrl], [ProducerId]) VALUES (18, 3, N'Foamposite "ParaNorman"', CAST(2750.00 AS Decimal(18, 2)), NULL, 3)
INSERT INTO [dbo].[Items] ([ItemId], [CategoryId], [Title], [Price], [ItemArtUrl], [ProducerId]) VALUES (19, 3, N'Foamposite "Tianjin"', CAST(2675.00 AS Decimal(18, 2)), NULL, 3)
INSERT INTO [dbo].[Items] ([ItemId], [CategoryId], [Title], [Price], [ItemArtUrl], [ProducerId]) VALUES (20, 4, N'Question mid', CAST(150.00 AS Decimal(18, 2)), NULL, 4)
INSERT INTO [dbo].[Items] ([ItemId], [CategoryId], [Title], [Price], [ItemArtUrl], [ProducerId]) VALUES (21, 4, N'Question mid "Teyana Taylor"', CAST(90.00 AS Decimal(18, 2)), NULL, 4)
INSERT INTO [dbo].[Items] ([ItemId], [CategoryId], [Title], [Price], [ItemArtUrl], [ProducerId]) VALUES (23, 4, N'Question mid Packer "Curtain Call" ', CAST(130.00 AS Decimal(18, 2)), NULL, 4)
INSERT INTO [dbo].[Items] ([ItemId], [CategoryId], [Title], [Price], [ItemArtUrl], [ProducerId]) VALUES (24, 4, N'Question mid "Crocus"', CAST(225.00 AS Decimal(18, 2)), NULL, 4)
INSERT INTO [dbo].[Items] ([ItemId], [CategoryId], [Title], [Price], [ItemArtUrl], [ProducerId]) VALUES (25, 4, N'Question mid "Packer Shoes"', CAST(275.00 AS Decimal(18, 2)), N'', 4)
INSERT INTO [dbo].[Items] ([ItemId], [CategoryId], [Title], [Price], [ItemArtUrl], [ProducerId]) VALUES (26, 5, N' UA Curry 2', CAST(145.00 AS Decimal(18, 2)), NULL, 5)
INSERT INTO [dbo].[Items] ([ItemId], [CategoryId], [Title], [Price], [ItemArtUrl], [ProducerId]) VALUES (27, 5, N' UA Curry 2 "Surprise Party"', CAST(70.00 AS Decimal(18, 2)), NULL, 5)
INSERT INTO [dbo].[Items] ([ItemId], [CategoryId], [Title], [Price], [ItemArtUrl], [ProducerId]) VALUES (29, 5, N'UA Curry 2"All Star"', CAST(65.00 AS Decimal(18, 2)), NULL, 5)
INSERT INTO [dbo].[Items] ([ItemId], [CategoryId], [Title], [Price], [ItemArtUrl], [ProducerId]) VALUES (30, 5, N'UA Curry 4', CAST(130.00 AS Decimal(18, 2)), NULL, 5)
INSERT INTO [dbo].[Items] ([ItemId], [CategoryId], [Title], [Price], [ItemArtUrl], [ProducerId]) VALUES (31, 5, N'UA Curry 4 "More Magic"', CAST(425.00 AS Decimal(18, 2)), NULL, 5)
SET IDENTITY_INSERT [dbo].[Items] OFF
