// <auto-generated />
namespace TheVault.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Messageadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Messageadded));
        
        string IMigrationMetadata.Id
        {
            get { return "201803160341541_Message added "; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
