// <auto-generated />
namespace TheVault.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changestoidenitymodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changestoidenitymodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201803062012229_changes to idenity  model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
